### ISSUE TITLE
Lol, Excuse me, How can I use it，thank

### ISSUE THREAD

**Issue by Czj1997-02** [pip-services3-dart/pip-services3-rabbitmq-dart#1]

**Comment by banalna** [comment]
This module is currently under development. 
There are problems with the dart_amqp driver. You can use a similar module on .NET.

Module:
https://github.com/pip-services3-dotnet/pip-services3-rabbitmq-dotnet

Docs:
http://docs.pipservices.org/getting_started/recipes/rabbitmq/
http://docs.pipservices.org/toolkit_api/net/rabbitmq/

**Comment by Czj1997-02** [comment]
> 该模块目前正在开发中。 dart_amqp 驱动程序存在问题。您可以在 .NET 上使用类似的模块。
> 
> 模块： [https ://github.com/pip-services3-dotnet/pip-services3-rabbitmq-dotnet](https://github.com/pip-services3-dotnet/pip-services3-rabbitmq-dotnet)
> 
> 文档： http: [//docs.pipservices.org/getting_started/recipes/rabbitmq/ ](http://docs.pipservices.org/getting_started/recipes/rabbitmq/) http://docs.pipservices.org/toolkit_api/net/rabbitmq/

**Comment by Czj1997-02** [comment]
> 该模块目前正在开发中。 dart_amqp 驱动程序存在问题。您可以在.NET上使用类似的模块。
> 
> 模块： https://github.com/pip-services3-dotnet/pip-services3-rabbitmq-dotnet
> 
> 文档： [http://docs.pipservices.org/getting_started/recipes/rabbitmq/ ](http://docs.pipservices.org/getting_started/recipes/rabbitmq/) http://docs.pipservices.org/toolkit_api/net/rabbitmq/

thanks very much
